{% set name = "kiwi-hpy" %}
{% set version = "1.3.2.hpy" %}
{% set download = "1.3.2-hpy" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpyproject/kiwi-hpy/archive/{{ download }}.tar.gz
  sha256: ec87b58eaff0ca623f13586d3f6a3a1164e2275310a171244b3aaf4fd3c62f2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --global-option="--hpy-abi=universal" . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [python_implementation != "graalpy"]
    - {{ compiler('cxx') }}  # [python_implementation != "graalpy"]
  host:
    - python >=3.7
    - hpy >=0.0.4
    - pip
  run:
    - python >=3.7
    - hpy >=0.0.4

test:
  imports:
    - kiwisolver
  source_files:
    - py/tests
  commands:
    - pip check
    - pytest py/tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/hpyproject/kiwi-hpy
  summary: Efficient C++ implementation of the Cassowary constraint solving algorithm (HPy port)
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - timfel
