# the graalpy version implies the gp_python_version and hpy_version, so update these together
{% set version = "22.3.0" %}
{% set gp_python_version = "3.8.5" %}
{% set hpy_version = "0.0.4" %}

# Keep increasing the build_num until we get a new graalpy version. Do not reset
{% set build_num = "0" %}

{% set python_maj_min = ".".join(gp_python_version.split(".")[:2]) %}
{% set graalpy_abi = "".join(version.split(".")[:2]) %}

package:
  name: graalpy-meta
  version: {{ version }}

build:
  number: {{ build_num }}
  skip: true  # [win or osx]

outputs:
  - name: python
    version: {{ gp_python_version }}
    build:
      number: {{ build_num }}
      string: {{ build_num }}_{{ graalpy_abi }}_graalpy
      track_features:
        - graalpy
      run_exports:
        weak:
          - graalpy_{{ graalpy_distribution }} >={{ version }}
          - python_abi {{ python_maj_min }} *_graalpy{{ graalpy_abi }}
        noarch:
          - {{ pin_subpackage("python", max_pin="x.x", min_pin="x.x") }}
      skip: true  # [win or osx]
    requirements:
      host:
        - graalpy_{{ graalpy_distribution }} {{ version }}
      run:
        - graalpy_{{ graalpy_distribution }} {{ version }}
        - python_abi {{ python_maj_min }} *_graalpy{{ graalpy_abi }}
    test:
      commands:
        - python --version
        - test $(python -c "import sys; print('.'.join(str(i) for i in sys.version_info[:3]))") == "{{ gp_python_version }}"  # [unix]
        - test $(python -c "import sys; print(sys.implementation.name)") == "graalpy"  # [unix]

  - name: graalpy
    version: {{ version }}
    build:
      number: {{ build_num }}
      string: {{ build_num }}_graalpy{{ python_maj_min.replace(".", "") }}
      noarch: generic
      skip: true  # [win or osx]
    requirements:
      run:
        - python {{ gp_python_version }} {{ build_num }}_{{ graalpy_abi }}_graalpy
    test:
      commands:
        - graalpy --version

  - name: hpy
    version: {{ hpy_version }}
    build:
      number: {{ build_num }}
      string: {{ build_num }}_graalpy
      noarch: generic
      skip: true  # [win or osx]
    requirements:
      run:
        - graalpy_{{ graalpy_distribution }} {{ version }}
        - python {{ gp_python_version }} {{ build_num }}_{{ graalpy_abi }}_graalpy
        - python_abi {{ python_maj_min }} *_graalpy{{ graalpy_abi }}
    test:
      commands:
        - test $(python -c "import hpy.universal; print(hpy.universal.get_version()[0])") == "{{ hpy_version }}"   # [unix]

about:
  home: https://github.com/conda-forge/graalpy-meta-feedstock
  summary: Metapackage to select GraalPy as python implementation
  license: UPL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timfel
    - msimacek
